name = "findmerates"
compatibility_date = "2026-04-16"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "findmerates"
database_id = "d33cd776-7d95-484e-968e-20f4b1442cc0"
